### ISSUE TITLE
Update/add a DRX script to look at tuning changes

### ISSUE THREAD

**Issue by jaycedowell** [lwa-project/commissioning#13]
For the North Arm commissioning it would be useful to have a script, maybe as part of `checkTimetags.py` or `drxFilecheck.py`, that would report when/if the tuning frequencies change.

**Comment by ctaylor-physics** [comment]
Here's a trial run with these wonky data sets because the tunings seem goofed as it is. Seems to be working ok, I assume these warnings are supposed to display for each tuning change before the data under it.

_INTERFEROMETRY OBS:_
Filename: 060366_000199017
Date of First Frame: 2024-02-25 13:43:19.140309
Beam: 1
Tune/Pols: 4
Sample Rate: 19600000 Hz
Tuning Frequency: 63299999.963 Hz (1); 60000000.003 Hz (2)
 
   |           Clipping              |          Power          |
   |      1X      1Y      2X      2Y |    1X    1Y    2X    2Y |
---+---------------------------------+-------------------------+
WARNING: Tuning 1 changed from 63299999.963 Hz to 56999999.973 Hz
WARNING: Tuning 2 changed from 60000000.003 Hz to 73799999.976 Hz
 1 |   0.00%   0.00%   0.00%   0.00% |  2.81  2.80  2.70  2.70 |
---+---------------------------------+-------------------------+
 M |   0.00%   0.00%   0.00%   0.00% |  2.81  2.80  2.70  2.70 |

**Comment by jaycedowell** [comment]
Seems to be working.
